AspNetShop/AspNetShop/ViewModels/CarsListViewModel.cs
using AspNetShop.Data.Models;
using System.Collections.Generic;

namespace AspNetShop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<CarModel> AllCars { get; set; }
        public string CurrentCategory { get; set; }
    }
}

AspNetShop/AspNetShop/ViewModels/HomeViewModel.cs
using AspNetShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<CarModel> FavCars { get; set; }
    }
}

AspNetShop/AspNetShop/ViewModels/ShopCartViewModel.cs
using AspNetShop.Data.Models;

namespace AspNetShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

AspNetShop/AspNetShop/Controllers/CarsController.cs
using AspNetShop.Data.Interfaces;
using AspNetShop.Data.Models;
using AspNetShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AspNetShop.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars allCars, ICarsCategory allCategories)
        {
            _allCars = allCars;
            _allCategories = allCategories;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            IEnumerable<CarModel> cars = null;
            var currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.AllCars.OrderBy(i => i.Id);
            }
            else
            {
                if (string.Equals("electro", category, System.StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.AllCars.Where(i => i.Category.CategoryName.Equals("Elector cars")).OrderBy(i => i.Id);
                    currCategory = "Електро";
                }
                else if (string.Equals("fuel", category, System.StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.AllCars.Where(i => i.Category.CategoryName.Equals("Classic cars")).OrderBy(i => i.Id);
                    currCategory = "Коптілки";
                }
            }
            var csrVM = new CarsListViewModel
            {
                AllCars = cars,
                CurrentCategory = currCategory
            };

            ViewBag.Title = "Сторінка з автомобілями";

            return View(csrVM);
        }
    }
}

AspNetShop/AspNetShop/Controllers/HomeController.cs
using AspNetShop.Data.Interfaces;
using AspNetShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars carRepository;

        public HomeController(IAllCars carRepository)
        {
            this.carRepository = carRepository;
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                FavCars = carRepository.GetFavCars
            };
            return View(homeCars);
        }
    }
}

AspNetShop/AspNetShop/Controllers/OrderController.cs
using AspNetShop.Data.Interfaces;
using AspNetShop.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspNetShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel order)
        {
            shopCart.ListShopItems = shopCart.GetShopItems();

            if(shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас мають бути товари!");
            }

            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Замовлення успішно оброблене";
            return View();
        }
    }
}

AspNetShop/AspNetShop/Controllers/ShopCartController.cs
using AspNetShop.Data.Interfaces;
using AspNetShop.Data.Models;
using AspNetShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace AspNetShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars carRepository;
        private readonly ShopCart shopCart;

        public ShopCartController(IAllCars carRepository, ShopCart shopCart)
        {
            this.carRepository = carRepository;
            this.shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = shopCart.GetShopItems();
            shopCart.ListShopItems = items;

            var viewModel = new ShopCartViewModel
            {
                ShopCart = shopCart
            };

            return View(viewModel);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = carRepository.AllCars.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                shopCart.AddToCart(item, 1);
            }
            return RedirectToAction("Index");
        }
    }
}

AspNetShop/AspNetShop/Views/Cars/List.cshtml
@model CarsListViewModel

<h1>Всі автомобілі</h1>
<h3>@Model.CurrentCategory</h3>

<div class="row mt-5 mb-2">
    @{
        foreach (var car in Model.AllCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

AspNetShop/AspNetShop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Улюблені автомобілі</h1>

<div class="row mt-5 mb-2">
    @{
        foreach (var car in Model.FavCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

AspNetShop/AspNetShop/Views/Order/Checkout.cshtml
@model OrderModel

<div class="row">
    <h3>Оформлення замовлення</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-droup">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-droup">
            <label asp-for="SurName"></label>
            <div class="col-md-5">
                <input asp-for="SurName" class="form-control" />
                <span asp-validation-for="SurName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-droup">
            <label asp-for="Adress"></label>
            <div class="col-md-5">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-droup">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-droup">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершити замовлення" />
    </form>
</div>

AspNetShop/AspNetShop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

AspNetShop/AspNetShop/Views/Shared/AllCars.cshtml
@model CarModel

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.ShortDesc</p>
    <p>Ціна: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.Id">Добавити в корзину</a></p>
</div>

AspNetShop/AspNetShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">itProger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Тачки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Електро</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Бенз</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2022 Company, Inc. · <a href="#">Privacy</a>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

AspNetShop/AspNetShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach (var el in Model.ShopCart.ListShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Автомобіль:</b> @el.Car.Name<br />
            <b>Ціна:</b> @el.Car.Price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплата</a>
</div>